### PR TITLE
fix(utils.escapePath): better checking for cmd

### PR DESCRIPTION
**Pull request by wraithgar**
As per discussion here:
https://github.com/npm/git/commit/0038a9dbd56f5a550a4cab1a996eda5e67243680

### CODE REVIEW

**Comment by wraithgar** [comment]
@ferdinando-ferreira Does this look better?  Thanks for your time and attention on this, it is really appreciated.

**Review by nlf — APPROVED** [review]
this looks good to me!

**Comment by wraithgar** [comment]
I'm going to merge this in good faith and get it in to the `release-next` branch on the cli. We have till Thursday to pull the plug on it if y'all find something we missed.

**Comment by ferdinando-ferreira** [comment]
@wraithgar : looks great. To be sure I'll sync my fork, check if the tests pass on my win32 and see if there was no regression.

**Comment by ferdinando-ferreira** [comment]
@wraithgar, @nlf : all tests pass in my system. Considering I wrote https://github.com/npm/git/pull/19 to ensure a regression would fail that test it looks AOK to ship. Thanks for merging it! 

Next step: write a PR and present a case with the team managing https://github.com/nodejs/node that it would be valuable to fix it upstream to ensure other projects affected have a more straightforward path to solve it. 

It is not just `npm install` that fails with the same problem, but an assorted and seemingly random set of node related command line utilities, all sharing the same symptom and root cause.

```
c:\tests\git>npm run test

> @npmcli/git@2.0.7 test
> tap

 PASS  test/find.js 4 OK 283.472ms
 PASS  test/is.js 5 OK 203.494ms
 PASS  test/opts.js 3 OK 135.19ms
 PASS  test/lines-to-revs.js 22 OK 96.328ms
 PASS  test/index.js 1 OK 17.681ms
 PASS  test/is-clean.js 6 OK 2s
 PASS  test/revs.js 20 OK 3s
 PASS  test/should-retry.js 3 OK 13.676ms
 PASS  test/which.js 5 OK 1s
 PASS  test/spawn.js 6 OK 4s
 PASS  test/clone.js 119 OK 47s


  🌈 SUMMARY RESULTS 🌈


Suites:   11 passed, 11 of 11 completed
Asserts:  194 passed, of 194
Time:     56s
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |      100 |      100 |      100 |      100 |                   |
 clone.js         |      100 |      100 |      100 |      100 |                   |
 find.js          |      100 |      100 |      100 |      100 |                   |
 index.js         |      100 |      100 |      100 |      100 |                   |
 is-clean.js      |      100 |      100 |      100 |      100 |                   |
 is.js            |      100 |      100 |      100 |      100 |                   |
 lines-to-revs.js |      100 |      100 |      100 |      100 |                   |
 opts.js          |      100 |      100 |      100 |      100 |                   |
 revs.js          |      100 |      100 |      100 |      100 |                   |
 should-retry.js  |      100 |      100 |      100 |      100 |                   |
 spawn.js         |      100 |      100 |      100 |      100 |                   |
 which.js         |      100 |      100 |      100 |      100 |                   |
------------------|----------|----------|----------|----------|-------------------|
```

**Pull request merged**
